const IDEAS = [
  { "t": "Reviewing the sturdiest Switch case after a year of travel", "tags": ["gear","review"] },
  { "t": "The hidden button combo that remaps your controller on the fly", "tags": ["gear","tutorial"] },
  { "t": "Every Switch dock I've owned ranked by reliability", "tags": ["gear","review"] },
  { "t": "The weight difference between Joy-Cons and Pro Controller in hand", "tags": ["gear","education"] },
  { "t": "Side-by-side: every official Nintendo Switch colour released", "tags": ["gear"] },
  { "t": "I tested 6 screen protectors — one destroyed my screen", "tags": ["gear","review","story"] },
  { "t": "The carrying case that survived a luggage carousel", "tags": ["gear","story"] },
  { "t": "My full controller parts drawer — everything labelled", "tags": ["gear"] },
  { "t": "The mod kit that arrived completely wrong — and what I did", "tags": ["gear","story","comedy"] },
  { "t": "Rating every Joy-Con colour combo for aesthetics", "tags": ["gear","review"] },
  { "t": "The Switch stand that actually doesn't wobble", "tags": ["gear","review"] },
  { "t": "Testing cheap vs premium thumbstick caps — feel difference", "tags": ["gear","review"] },
  { "t": "The best angle to film your controller for TikTok", "tags": ["gear","tutorial","lifestyle"] },
  { "t": "Every single button on the Pro Controller explained", "tags": ["gear","education"] },
  { "t": "Why I store my game cards vertically not horizontally", "tags": ["gear","tutorial"] },
  { "t": "The rubber grip wrap that transformed my Switch Lite", "tags": ["gear","review"] },
  { "t": "Cleanest cable management behind a Switch dock — achieved", "tags": ["gear","lifestyle"] },
  { "t": "Building the perfect travel pouch from two separate purchases", "tags": ["gear","tutorial"] },
  { "t": "My modded controller under studio lighting — final reveal", "tags": ["gear"] },
  { "t": "The Joy-Con rail damage everyone ignores — how to prevent it", "tags": ["gear","tutorial","education"] },
  { "t": "Every ABXY button colour variant I've ever installed", "tags": ["gear"] },
  { "t": "The third-party Pro Controller I actually recommend", "tags": ["gear","review"] },
  { "t": "Rating Switch cases by how good they smell when new", "tags": ["gear","comedy","review"] },
  { "t": "The tiniest Switch accessory that makes the biggest difference", "tags": ["gear"] },
  { "t": "My complete soldering setup for Joy-Con mods", "tags": ["gear","tutorial"] },
  { "t": "Switch game cases ranked by how satisfying they are to open", "tags": ["gear"] },
  { "t": "The memory card that wiped my data — what to buy instead", "tags": ["gear","story","review"] },
  { "t": "How I keep my controllers dust-free between uses", "tags": ["gear","tutorial"] },
  { "t": "The difference between Switch V1 V2 and OLED hardware", "tags": ["gear","education"] },
  { "t": "Unboxing a limited edition controller I waited months for", "tags": ["gear","story"] },
  { "t": "My Switch charging station setup — 3 devices one spot", "tags": ["gear","lifestyle"] },
  { "t": "The mod screwdriver set that changed everything for me", "tags": ["gear","review"] },
  { "t": "Rating officially licensed vs third-party charging cables", "tags": ["gear","review"] },
  { "t": "My game card binder setup — every slot filled", "tags": ["gear"] },
  { "t": "The Joy-Con battery life test I ran for a week", "tags": ["gear","education"] },
  { "t": "How I sourced custom buttons for under $5 shipped", "tags": ["gear","tutorial"] },
  { "t": "The Switch Lite colour I wish Nintendo would bring back", "tags": ["gear","trend"] },
  { "t": "My controller mod side by side with the original factory look", "tags": ["gear"] },
  { "t": "The shock absorption test on 4 Switch cases — dropped from 1m", "tags": ["gear","review","challenge"] },
  { "t": "Every ergonomic grip I've tried for handheld mode", "tags": ["gear","review"] },
  { "t": "How a $3 part saved my Joy-Con from drift", "tags": ["gear","tutorial","story"] },
  { "t": "The Switch game I bought purely for the physical box art", "tags": ["gear","gaming"] },
  { "t": "Testing Switch performance with a fast vs slow SD card", "tags": ["gear","education"] },
  { "t": "The most fragile thing about the Switch nobody warns you about", "tags": ["gear","education"] },
  { "t": "Why I have two identical controllers for different games", "tags": ["gear","gaming"] },
  { "t": "The aesthetic switch case collection wall I built", "tags": ["gear","lifestyle"] },
  { "t": "My complete Joy-Con repair kit contents shown one by one", "tags": ["gear","tutorial"] },
  { "t": "The HDMI cable that actually matters for Switch performance", "tags": ["gear","education","review"] },
  { "t": "Limited edition Switch consoles ranked by resale value", "tags": ["gear","education"] },
  { "t": "How I photograph my gear for TikTok — the exact setup", "tags": ["gear","tutorial","lifestyle"] }
];

window.ALL_IDEAS = IDEAS;
